name: "CS 24 Spring 2017"
github_url: https://github.com/ucsb-cs24-sp17/ucsb-cs24-sp17.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

start_week: 1
start_date: 2017-04-02 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2017-04-03" },
  {"label":"Univ Holiday", "date":"2017-05-29" },
  {"label":"Last day of classes", "date":"2017-06-09" },			
  ]


course: "CS24"
legacy_wiki_name: 
legacy_wiki_url: 
qtr: "S17"
quarter: "Spring 2017"

kramdown:
   parse_block_html: true


exclude:
   - vendor

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: pa
    values:
      layout: pa
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


